APIs separated
AREA-team/edu-area pull request #31
Opened 2021-08-15 12:53 UTC by vacya01

APIs have been separated between apps.
Socket and users API moved to area app.
Other APIs moved to market app.

2021-08-15 17:11 UTC, markK24 commented on market/templates/market/create-company.html
> +        const imageUploadEndpoint = "{{ url('market.market-api.uploadImage') }}"
😬

2021-08-15 17:15 UTC, markK24 requested changes
I don't understand the purpose. It was better before, now the paths are too long, easier to get lost

2021-08-15 18:59 UTC, vacya01 commented
Noticed a decrease in the speed of the site

2021-08-16 08:03 UTC, vacya01 commented on market/templates/market/create-company.html
> +        const imageUploadEndpoint = "{{ url('market.market-api.uploadImage') }}"
Changed to "market.api.uploadImage"

2021-08-16 08:08 UTC, markK24 approved these changes

2021-08-16 10:39 UTC, merged